# Generated by Django 2.1.15 on 2020-09-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VmsDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_serial', models.IntegerField(verbose_name='시리얼번호')),
                ('dev_name', models.CharField(max_length=100, verbose_name='기기이름')),
                ('model_id', models.IntegerField(verbose_name='모델아이디')),
                ('vms_id', models.IntegerField(verbose_name='vms아이디')),
                ('dev_type', models.CharField(max_length=45, verbose_name='기기타입')),
                ('dev_stat', models.CharField(max_length=45, verbose_name='기기상태')),
                ('ins_time', models.DateTimeField(verbose_name='데이터삽입시간')),
                ('mod_time', models.DateTimeField(verbose_name='모드시간')),
                ('sdc_ins_time', models.DateTimeField(verbose_name='INSERT시간')),
                ('sdc_upd_time', models.DateTimeField(verbose_name='UPDATE시간')),
            ],
            options={
                'verbose_name': 'VMS DEVICE',
                'verbose_name_plural': 'VMS DEVICE',
                'db_table': 'vms_device',
            },
        ),
    ]
