# Generated by Django 2.1.15 on 2020-09-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VmsCommonCodeRef2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(verbose_name='타입아이디')),
                ('code_id', models.IntegerField(verbose_name='코드아이디')),
                ('code_name', models.CharField(max_length=50, verbose_name='코드이름')),
            ],
            options={
                'verbose_name': 'VMS COMMON CODE REF',
                'verbose_name_plural': 'VMS COMMON CODE REF',
                'db_table': 'vms_common_code_ref_2',
            },
        ),
        migrations.CreateModel(
            name='VmsDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_serial', models.IntegerField(verbose_name='시리얼번호')),
                ('dev_name', models.CharField(max_length=100, verbose_name='기기이름')),
                ('model_id', models.IntegerField(blank=True, null=True, verbose_name='모델아이디')),
                ('vms_id', models.IntegerField(blank=True, null=True, verbose_name='vms아이디')),
                ('dev_type', models.CharField(blank=True, max_length=45, null=True, verbose_name='기기타입')),
                ('dev_stat', models.CharField(blank=True, max_length=45, null=True, verbose_name='기기상태')),
                ('longitude', models.CharField(blank=True, max_length=45, null=True, verbose_name='경도')),
                ('latitude', models.CharField(blank=True, max_length=45, null=True, verbose_name='위도')),
                ('ins_time', models.DateTimeField(blank=True, null=True, verbose_name='데이터삽입시간')),
                ('mod_time', models.DateTimeField(blank=True, null=True, verbose_name='모드시간')),
                ('sdc_ins_time', models.DateTimeField(blank=True, null=True, verbose_name='INSERT시간')),
                ('sdc_upd_time', models.DateTimeField(blank=True, null=True, verbose_name='UPDATE시간')),
            ],
            options={
                'verbose_name': 'VMS DEVICE',
                'verbose_name_plural': 'VMS DEVICE',
                'db_table': 'vms_device',
            },
        ),
        migrations.CreateModel(
            name='VmsDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField(verbose_name='모델아이디')),
                ('model_name', models.CharField(max_length=45, verbose_name='모델이름')),
                ('company', models.CharField(blank=True, max_length=45, null=True, verbose_name='회사')),
                ('model_driver', models.CharField(blank=True, max_length=45, null=True, verbose_name='모델드라이버')),
                ('ins_time', models.DateTimeField(blank=True, null=True, verbose_name='데이터삽입시간')),
                ('mod_time', models.DateTimeField(blank=True, null=True, verbose_name='모드시간')),
                ('sdc_ins_time', models.DateTimeField(blank=True, null=True, verbose_name='INSERT시간')),
                ('sdc_upd_time', models.DateTimeField(blank=True, null=True, verbose_name='UPDATE시간')),
            ],
            options={
                'verbose_name': 'VMS DEVICE MODEL',
                'verbose_name_plural': 'VMS DEVICE MODEL',
                'db_table': 'vms_device_model',
            },
        ),
    ]
